import type { CapabilityDef, Department, RoleDefinition } from "./index.js";

/**
 * The capability catalog (see docs/company-os.md §6). Curated data the generator
 * selects from — departments, roles, the skills they carry, and the capabilities
 * (tools/connectors) they may use, each tagged with risk. Extend the *data*, not
 * the code, to cover more departments and skills.
 */

export const DEPARTMENTS: Department[] = [
  "exec",
  "product",
  "engineering",
  "design",
  "data",
  "ai",
  "growth",
  "marketing",
  "sales",
  "support",
  "success",
  "ops",
  "finance",
  "legal",
  "people",
  "logistics",
];

/** Everything an employee can *do*, with the risk it carries (docs/company-os.md §8). */
export const CAPABILITIES: CapabilityDef[] = [
  { id: "research.web", kind: "tool", risk: "none", description: "Search and read the web" },
  { id: "files.read", kind: "tool", risk: "none", description: "Read workspace files/artifacts" },
  { id: "files.write", kind: "tool", risk: "none", description: "Write workspace files/artifacts" },
  { id: "browser.use", kind: "tool", risk: "none", description: "Drive a browser sandbox" },
  { id: "code.run", kind: "tool", risk: "none", description: "Run code in a sandbox" },
  { id: "repo.write", kind: "connector", risk: "consequential", description: "Open PRs / write to a repo" },
  { id: "deploy.production", kind: "connector", risk: "consequential", description: "Deploy to production" },
  { id: "social.read_insights", kind: "connector", risk: "none", description: "Read social analytics" },
  { id: "social.publish", kind: "connector", risk: "consequential", description: "Publish social posts" },
  { id: "social.reply", kind: "connector", risk: "consequential", description: "Reply to comments / DMs" },
  { id: "email.send", kind: "connector", risk: "consequential", description: "Send email" },
  { id: "ads.manage", kind: "connector", risk: "money", description: "Create / boost ads" },
  { id: "payments.charge", kind: "connector", risk: "money", description: "Charge a customer" },
];

/** Skill ids the catalog roles draw from (merged with the built-in skill packs later). */
export const CATALOG_SKILLS: Array<{ id: string; name: string }> = [
  { id: "web-research", name: "Web research" },
  { id: "writing", name: "Writing" },
  { id: "copywriting", name: "Copywriting" },
  { id: "seo", name: "SEO" },
  { id: "social-media", name: "Social media" },
  { id: "paid-ads", name: "Paid ads" },
  { id: "sales-outreach", name: "Sales outreach" },
  { id: "crm", name: "CRM" },
  { id: "product-spec", name: "Product specs" },
  { id: "roadmap", name: "Roadmapping" },
  { id: "ux-design", name: "UX design" },
  { id: "visual-design", name: "Visual design" },
  { id: "frontend", name: "Frontend" },
  { id: "backend", name: "Backend" },
  { id: "devops", name: "DevOps" },
  { id: "qa-testing", name: "QA testing" },
  { id: "data-analysis", name: "Data analysis" },
  { id: "finance-tracking", name: "Finance tracking" },
  { id: "customer-support", name: "Customer support" },
  { id: "recruiting", name: "Recruiting" },
  { id: "legal-review", name: "Legal / compliance" },
];

/**
 * Seed roles across the core departments. `reportsTo` references another role id
 * ("exec.ceo" = the chair). The generator selects + tailors these; the CEO approves.
 */
export const ROLE_CATALOG: RoleDefinition[] = [
  {
    id: "exec.ceo",
    title: "CEO",
    department: "exec",
    level: "exec",
    summary: "Sets direction, prioritises, delegates, and reports to the human owner.",
    jobDescription:
      "You are the CEO. Own the company goal, plan the work, delegate to department heads, unblock them, and report to the human owner with short, decisive status.",
    skills: ["web-research", "writing", "roadmap"],
    capabilities: ["research.web", "files.read", "files.write"],
    kpis: ["Goal progress", "Decisions made", "Blockers cleared"],
  },
  {
    id: "product.manager",
    title: "Head of Product",
    department: "product",
    level: "head",
    summary: "Owns the product roadmap and turns goals into clear, small tasks.",
    jobDescription:
      "You own the product roadmap. Turn the company goal into specs and small, well-scoped tasks; define what 'done' means and prioritise the backlog.",
    skills: ["product-spec", "roadmap", "data-analysis"],
    capabilities: ["research.web", "files.read", "files.write"],
    kpis: ["Shipped scope", "Spec quality", "Backlog health"],
    reportsTo: "exec.ceo",
  },
  {
    id: "product.analyst",
    title: "Business Analyst",
    department: "product",
    level: "ic",
    summary: "Researches the market and turns findings into requirements.",
    jobDescription:
      "You analyse the market and customers and turn findings into concrete requirements the team can build.",
    skills: ["web-research", "product-spec", "data-analysis"],
    capabilities: ["research.web", "files.read", "files.write"],
    kpis: ["Requirements delivered"],
    reportsTo: "product.manager",
  },
  {
    id: "product.researcher",
    title: "Product Researcher",
    department: "product",
    level: "ic",
    summary: "Studies users and competitors to inform the roadmap.",
    jobDescription:
      "You research users and competitors, summarise what matters, and bring evidence to prioritisation decisions.",
    skills: ["web-research", "writing"],
    capabilities: ["research.web", "files.read", "files.write"],
    kpis: ["Research briefs"],
    reportsTo: "product.manager",
  },
  {
    id: "engineering.cto",
    title: "CTO",
    department: "engineering",
    level: "head",
    summary: "Owns the engineering plan and technical decisions.",
    jobDescription:
      "You lead engineering. Choose the architecture, break the plan into tasks, assign engineers/QA, review the result, and explain trade-offs before building.",
    skills: ["backend", "frontend", "devops"],
    capabilities: ["code.run", "files.read", "files.write", "repo.write"],
    kpis: ["Delivery", "Reliability", "Code quality"],
    reportsTo: "exec.ceo",
  },
  {
    id: "engineering.backend",
    title: "Backend Engineer",
    department: "engineering",
    level: "ic",
    summary: "Builds and tests services and APIs.",
    jobDescription:
      "You build backend services and APIs, write tests, and hand over a working, tested change.",
    skills: ["backend", "qa-testing"],
    capabilities: ["code.run", "files.read", "files.write", "repo.write"],
    kpis: ["Tasks delivered", "Tests passing"],
    reportsTo: "engineering.cto",
  },
  {
    id: "engineering.frontend",
    title: "Frontend Engineer",
    department: "engineering",
    level: "ic",
    summary: "Builds and tests the user interface.",
    jobDescription: "You build the user interface, wire it to APIs, and test it.",
    skills: ["frontend", "qa-testing"],
    capabilities: ["code.run", "files.read", "files.write", "repo.write"],
    kpis: ["Tasks delivered", "Tests passing"],
    reportsTo: "engineering.cto",
  },
  {
    id: "engineering.devops",
    title: "DevOps Engineer",
    department: "engineering",
    level: "ic",
    summary: "Owns build, deploy, and reliability.",
    jobDescription:
      "You own build, deploy and reliability. Propose deployments for approval and keep environments healthy.",
    skills: ["devops"],
    capabilities: ["code.run", "files.read", "files.write", "deploy.production"],
    kpis: ["Uptime", "Deploy success"],
    reportsTo: "engineering.cto",
  },
  {
    id: "engineering.qa",
    title: "QA Engineer",
    department: "engineering",
    level: "ic",
    summary: "Tests work before it ships.",
    jobDescription:
      "You test deliverables against the spec, file clear bugs, and verify fixes before they ship.",
    skills: ["qa-testing"],
    capabilities: ["code.run", "browser.use", "files.read", "files.write"],
    kpis: ["Bugs caught", "Coverage"],
    reportsTo: "engineering.cto",
  },
  {
    id: "design.ux",
    title: "UX Designer",
    department: "design",
    level: "ic",
    summary: "Designs flows and interfaces.",
    jobDescription: "You design user flows and interfaces that match the brand and the goal.",
    skills: ["ux-design", "visual-design"],
    capabilities: ["files.read", "files.write", "browser.use"],
    kpis: ["Designs delivered"],
    reportsTo: "product.manager",
  },
  {
    id: "design.visual",
    title: "Visual Designer",
    department: "design",
    level: "ic",
    summary: "Produces on-brand visuals and posters.",
    jobDescription:
      "You produce on-brand visuals (posters, covers) using the brand kit, saved as artifacts.",
    skills: ["visual-design", "copywriting"],
    capabilities: ["files.read", "files.write", "code.run"],
    kpis: ["Assets delivered", "Brand consistency"],
    reportsTo: "exec.ceo",
  },
  {
    id: "data.analyst",
    title: "Data Analyst",
    department: "data",
    level: "ic",
    summary: "Tracks metrics and turns data into decisions.",
    jobDescription: "You track the company's metrics and turn them into clear, honest reporting.",
    skills: ["data-analysis"],
    capabilities: ["research.web", "code.run", "files.read", "files.write"],
    kpis: ["Reports delivered", "Metric accuracy"],
    reportsTo: "exec.ceo",
  },
  {
    id: "ai.engineer",
    title: "AI Engineer",
    department: "ai",
    level: "ic",
    summary: "Builds AI features and evaluates models.",
    jobDescription:
      "You build and evaluate AI features, pick sensible models, and guard against hallucinations and cost.",
    skills: ["backend", "data-analysis"],
    capabilities: ["code.run", "files.read", "files.write", "repo.write"],
    kpis: ["AI features delivered"],
    reportsTo: "engineering.cto",
  },
  {
    id: "marketing.manager",
    title: "Head of Marketing",
    department: "marketing",
    level: "head",
    summary: "Owns positioning, content and channels.",
    jobDescription:
      "You own marketing: positioning, content, channels and campaigns. Draft everything; publishing and spend need approval.",
    skills: ["copywriting", "seo", "social-media"],
    capabilities: ["research.web", "files.read", "files.write", "social.read_insights", "social.publish", "email.send"],
    kpis: ["Reach", "Content shipped", "Pipeline influenced"],
    reportsTo: "exec.ceo",
  },
  {
    id: "marketing.content",
    title: "Content Manager",
    department: "marketing",
    level: "ic",
    summary: "Writes posts, articles and copy.",
    jobDescription: "You write posts, articles and copy in the company's tone, and prepare them for approval.",
    skills: ["copywriting", "writing", "seo"],
    capabilities: ["research.web", "files.read", "files.write"],
    kpis: ["Content delivered"],
    reportsTo: "marketing.manager",
  },
  {
    id: "marketing.social",
    title: "Social Media Manager",
    department: "marketing",
    level: "ic",
    summary: "Runs the social channels.",
    jobDescription:
      "You run the social channels: draft and schedule posts, read analytics, and reply to comments (publishing and replies need approval).",
    skills: ["social-media", "copywriting"],
    capabilities: ["research.web", "files.read", "files.write", "social.read_insights", "social.publish", "social.reply"],
    kpis: ["Engagement", "Posting cadence"],
    reportsTo: "marketing.manager",
  },
  {
    id: "marketing.seo",
    title: "SEO Specialist",
    department: "marketing",
    level: "ic",
    summary: "Grows organic traffic.",
    jobDescription: "You improve organic discoverability: keywords, on-page, and content plans.",
    skills: ["seo", "copywriting", "data-analysis"],
    capabilities: ["research.web", "files.read", "files.write"],
    kpis: ["Organic traffic"],
    reportsTo: "marketing.manager",
  },
  {
    id: "sales.manager",
    title: "Head of Sales",
    department: "sales",
    level: "head",
    summary: "Owns the pipeline and outreach.",
    jobDescription:
      "You own the sales pipeline: prioritise leads, own outreach, and bring deals to the CEO. Sending needs approval.",
    skills: ["sales-outreach", "crm"],
    capabilities: ["research.web", "files.read", "files.write", "email.send"],
    kpis: ["Pipeline", "Deals closed"],
    reportsTo: "exec.ceo",
  },
  {
    id: "sales.rep",
    title: "Sales Representative",
    department: "sales",
    level: "ic",
    summary: "Works leads and drafts outreach.",
    jobDescription: "You research leads, draft personalised outreach, and reply — drafts first, sends on approval.",
    skills: ["sales-outreach", "crm", "writing"],
    capabilities: ["research.web", "files.read", "files.write", "email.send"],
    kpis: ["Reply rate", "Meetings booked"],
    reportsTo: "sales.manager",
  },
  {
    id: "sales.researcher",
    title: "Lead Researcher",
    department: "sales",
    level: "ic",
    summary: "Finds and enriches leads.",
    jobDescription: "You find and enrich qualified leads and keep the CRM tidy.",
    skills: ["web-research", "crm"],
    capabilities: ["research.web", "files.read", "files.write"],
    kpis: ["Qualified leads"],
    reportsTo: "sales.manager",
  },
  {
    id: "support.agent",
    title: "Support Agent",
    department: "support",
    level: "ic",
    summary: "Answers customer questions.",
    jobDescription:
      "You answer customer questions, draft replies, and keep the knowledge base current. Sending needs approval.",
    skills: ["customer-support", "writing"],
    capabilities: ["files.read", "files.write", "social.reply", "email.send"],
    kpis: ["Response time", "Resolution"],
    reportsTo: "success.manager",
  },
  {
    id: "success.manager",
    title: "Customer Success Manager",
    department: "success",
    level: "head",
    summary: "Keeps customers successful and retained.",
    jobDescription: "You own onboarding and retention: check in, unblock customers, and reduce churn.",
    skills: ["customer-support", "crm"],
    capabilities: ["files.read", "files.write", "email.send"],
    kpis: ["Retention", "Satisfaction"],
    reportsTo: "exec.ceo",
  },
  {
    id: "ops.manager",
    title: "Head of Operations",
    department: "ops",
    level: "head",
    summary: "Keeps the company running smoothly.",
    jobDescription:
      "You run operations: track deadlines, risks and processes, and flag anything the CEO must approve.",
    skills: ["data-analysis", "writing"],
    capabilities: ["files.read", "files.write"],
    kpis: ["On-time delivery", "Risks surfaced"],
    reportsTo: "exec.ceo",
  },
  {
    id: "finance.analyst",
    title: "Finance Analyst",
    department: "finance",
    level: "ic",
    summary: "Tracks spend, revenue and budgets.",
    jobDescription: "You track spend, revenue and the budget, and report the numbers honestly.",
    skills: ["finance-tracking", "data-analysis"],
    capabilities: ["files.read", "files.write"],
    kpis: ["Budget adherence", "Accuracy"],
    reportsTo: "exec.ceo",
  },
  {
    id: "legal.compliance",
    title: "Compliance Officer",
    department: "legal",
    level: "ic",
    summary: "Checks compliance and terms of service.",
    jobDescription: "You review work for legal/compliance risk and platform terms, and flag issues.",
    skills: ["legal-review", "writing"],
    capabilities: ["research.web", "files.read", "files.write"],
    kpis: ["Risks flagged"],
    reportsTo: "exec.ceo",
  },
  {
    id: "people.recruiter",
    title: "Recruiter",
    department: "people",
    level: "ic",
    summary: "Plans hiring and drafts role definitions.",
    jobDescription: "You plan hiring needs and draft new role definitions for the CEO to approve.",
    skills: ["recruiting", "writing"],
    capabilities: ["files.read", "files.write"],
    kpis: ["Roles proposed"],
    reportsTo: "ops.manager",
  },
  {
    id: "logistics.coordinator",
    title: "Logistics Coordinator",
    department: "logistics",
    level: "ic",
    summary: "Coordinates suppliers and delivery.",
    jobDescription: "You coordinate suppliers and delivery for the company's operations.",
    skills: ["data-analysis", "writing"],
    capabilities: ["research.web", "files.read", "files.write"],
    kpis: ["Deliveries on time"],
    reportsTo: "ops.manager",
  },
];
